seed_everything: 47
trainer:

  default_root_dir: ./results/vector_chexpert_disease_classification_77
  accelerator: cuda
  devices: 1
  log_every_n_steps: 1
  max_epochs: 100

  callbacks:
  - class_path: lightning.pytorch.callbacks.RichProgressBar
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
        monitor: 'val_loss'
        patience: 5
        mode: 'min'  # or 'max' depending on your metric
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
        monitor: 'val_loss'
        mode: 'min'  # or 'max' depending on your metric
        save_top_k: 1  # save only the best checkpoint
        dirpath: './results/vector_chexpert_disease_classification_77/checkpoints/'
        filename: 'best_val_loss-{epoch:02d}-{val_loss:.4f}'
  
data: # data.moudle.DataModule
  train_dataset:
    class_path: data.vector.dataset_class.VectorXrayDataset
    init_args:
      dataframe_path: ./dataset/chexpert/cxp_train_df.csv
      path_vector: ./dataset/vector_embeddings/
  val_dataset:
    class_path: data.vector.dataset_class.VectorXrayDataset
    init_args:
      dataframe_path: ./dataset/chexpert/cxp_validation_df.csv
      path_vector: ./dataset/vector_embeddings/
  test_dataset:
    class_path: data.vector.dataset_class.VectorXrayDataset
    init_args:
      dataframe_path: ./dataset/chexpert/cxp_test_df.csv
      path_vector: ./dataset/vector_embeddings/

  batch_size: 48
  num_workers: 38
  prediction_on: "val"


model: # models.module.CLS
  model:
    class_path: models.vector.models.MLPModel
    init_args:
      embeddings_size: 1376
      hidden_layer_sizes: [768,256]
      dropout_rate: 0.3
      num_classes: 14
  lr : 0.0001
  criterion: # torch.nn.BCEWithLogitsLoss
    class_path: torch.nn.BCEWithLogitsLoss
  weight_decay: 0.00001
  prediction_on: "val"
  save_probabilities_path: ./results/vector_chexpert_disease_classification_77/probabilities