seed_everything: 19

trainer:
  default_root_dir: ./results/chexpert_all/
  accelerator: gpu
  devices: 1  # Change this number to the number of GPUs you have
  # strategy: ddp
  max_epochs: 100

  callbacks:
  - class_path: lightning.pytorch.callbacks.RichProgressBar
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
        monitor: 'val_loss'
        patience: 10
        mode: 'min'  # or 'max' depending on your metric
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
        monitor: 'val_loss'
        mode: 'min'  # or 'max' depending on your metric
        save_top_k: 20  # save only the best checkpoint
        dirpath: ${trainer.default_root_dir}checkpoints/
        filename: 'best_val_loss-{epoch:02d}-{val_loss:.4f}'

  

data: # data.moudle.DataModule
  global_variable:
    image_root_path: /local/data/physionet.org/files/CheXpert-v1.0/
    csv_root: /local/home/hhamidi/project/med-stable-diffusion/data/csv/chexpert/chexpert
    image_root_path_syn: /local/data/syn_samples/sample_from_chexpert_train_label_last2/
    csv_root_syn: /local/data/syn_samples/sample_from_chexpert_train_label_last2/
  train_dataset:
    class_path: torch.utils.data.ConcatDataset
    init_args:
      datasets:
        - class_path: data.image.dataset_class.CheXpert_Advanced
          init_args:
            csv_path: ${data.global_variable.csv_root}_train.csv
            image_root_path: ${data.global_variable.image_root_path}
            train_cols:
              - Cardiomegaly
              - Edema
              - Consolidation
              - Atelectasis
              - Pleural Effusion
              - No Finding
            use_upsampling: True
            use_frontal: True
            image_size: 224
            mode: train
            class_index: -1
        - class_path: data.image.dataset_class.CheXpert_Advanced
          init_args:
            csv_path: ${data.global_variable.csv_root_syn}samples.csv
            image_root_path: ${data.global_variable.image_root_path_syn}
            train_cols:
              - Cardiomegaly
              - Edema
              - Consolidation
              - Atelectasis
              - Pleural Effusion
              - No Finding
            use_upsampling: True
            use_frontal: True
            image_size: 224
            mode: train
            class_index: -1
            split_size: 1.0


  val_dataset:
    class_path: data.image.dataset_class.CheXpert_Advanced
    init_args:
        csv_path: ${data.global_variable.csv_root}_val.csv
        image_root_path: ${data.global_variable.image_root_path}
        train_cols:
          - Cardiomegaly
          - Edema
          - Consolidation
          - Atelectasis
          - Pleural Effusion
          - No Finding
        use_upsampling: False
        use_frontal: True
        image_size: 224
        mode: test
        class_index: -1
  test_dataset:
    class_path: data.image.dataset_class.CheXpert_Advanced
    init_args:
        csv_path: ${data.global_variable.csv_root}_test.csv
        image_root_path: ${data.global_variable.image_root_path}
        train_cols:
          - Cardiomegaly
          - Edema
          - Consolidation
          - Atelectasis
          - Pleural Effusion
          - No Finding
        use_upsampling: False
        use_frontal: True
        image_size: 224
        mode: test
        class_index: -1


  batch_size: 32
  num_workers: 8
  prediction_on: "test"


model: # models.module.CLS
  model:
    class_path: models.image.models.DensNetWithHead
    init_args:
      hidden_layer_sizes: [768,128]
      dropout_rate: 0.1
      num_classes: 6
  criterion: # torch.nn.BCEWithLogitsLoss
    class_path: torch.nn.BCEWithLogitsLoss
  weight_decay: 0.0
  prediction_on: "test"
  save_probabilities_path: ${trainer.default_root_dir}probabilities/
  lr: 0.0001

  #CUDA_VISIBLE_DEVICES=1  python main.py fit -c /local/home/hhamidi/fairness_on_embeddings/configs/chexpert_all.yaml