trainer:
  default_root_dir: ./results/vector_train_all_test_all
  accelerator: cuda
  devices: 1
  log_every_n_steps: 1
  max_epochs: 100

  callbacks:
    - class_path: lightning.pytorch.callbacks.RichProgressBar
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: 'val_loss'
        patience: 5
        mode: 'min'  # or 'max' depending on your metric
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: 'val_loss'
        mode: 'min'  # or 'max' depending on your metric
        save_top_k: 1  # save only the best checkpoint
        dirpath: ./results/vector_train_all_test_all/checkpoints
        filename: 'best_val_loss-{epoch:02d}-{val_loss:.4f}'

data: #data.DataModule
#def __init__(self, info_df_path_mimic, info_df_path_chexpert, data_path_mimic, data_path_chexpert):
  train_dataset:
    class_path: data.vec.dataset_class.VecDataset_All
    init_args:
      info_df_path_mimic:  /fs01/home/hhamidi/clean_image/datasets/final_csv/train_mimic.csv
      info_df_path_chexpert: /fs01/home/hhamidi/clean_image/datasets/final_csv/train_chexpert.csv
      data_path_mimic: /fs01/home/hhamidi/pytorch_lightning/clean/datasets/mimic-cxr/files
      data_path_chexpert: /fs01/home/hhamidi/clean_image/datasets/cp
  val_dataset:
    class_path: data.vec.dataset_class.VecDataset_All
    init_args:
      info_df_path_mimic:  /fs01/home/hhamidi/clean_image/datasets/final_csv/val_mimic.csv
      info_df_path_chexpert: /fs01/home/hhamidi/clean_image/datasets/final_csv/val_chexpert.csv
      data_path_mimic: /fs01/home/hhamidi/pytorch_lightning/clean/datasets/mimic-cxr/files
      data_path_chexpert: /fs01/home/hhamidi/clean_image/datasets/cp
  test_dataset:
    class_path: data.vec.dataset_class.VecDataset_All
    init_args:
      info_df_path_mimic:  /fs01/home/hhamidi/clean_image/datasets/final_csv/test_mimic.csv
      info_df_path_chexpert: /fs01/home/hhamidi/clean_image/datasets/final_csv/test_chexpert.csv
      data_path_mimic: /fs01/home/hhamidi/pytorch_lightning/clean/datasets/mimic-cxr/files
      data_path_chexpert: /fs01/home/hhamidi/clean_image/datasets/cp
      
  batch_size: 256
  num_workers: 35
  prediction_on: "val"

model: # models.module.CLS
  model:
    class_path: models.vec.models.CustomModel
    init_args:
      embeddings_size: 1376
      hidden_layer_sizes: [768,256,128,64]
      dropout_rate: 0.1
      num_classes: 14
  criterion: #
    class_path: torch.nn.BCEWithLogitsLoss
  prediction_on: "val"
  save_probabilities_path: ./results/vector_train_all_test_all/probabilities